# Generated by Django 3.2 on 2021-04-21 15:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='non', max_length=50)),
                ('pullups', models.CharField(default='non', max_length=50)),
                ('situps', models.CharField(default='non', max_length=50)),
                ('runtime', models.CharField(default='non', max_length=50)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
